FROM alpine:3.8

RUN mkdir -p /app && \
  apk --no-cache add elixir && \
  apk --update --no-cache add erlang-runtime-tools && \
  mix local.hex --force && \
  mix local.rebar --force

VOLUME ["/app"]

WORKDIR "/app"

EXPOSE 4000

CMD ["iex"]
