FROM elixir:1.6-alpine

ENV API_VERSION 0.0.1
ENV MIX_HOST 8080

RUN mkdir /app && \
  apk --no-cache add tar bash

COPY ./archives/api_${API_VERSION}.tar.gz /app/api.tar.gz

RUN cd /app && \
  tar -zxvf /app/api.tar.gz && \
  rm /app/api.tar.gz && \
  apk del tar && \
  rm -rf /var/cache/apk/*

WORKDIR /app/releases/${API_VERSION}

EXPOSE $MIX_HOST
VOLUME /app

CMD ["./togebuild.sh", "foreground"]
